### ISSUE TITLE
When using tower_error_tracker, `ErrorTracker.set_context` doesn't work

### ISSUE THREAD

**Issue by brainlid** [mimiquate/tower_error_tracker#19]
Elixir: 1.17.2
OTP: 27

In my `mix.exs` file, when I have: 

```elixir
{:tower_email, "~> 0.5.2"},
{:tower_error_tracker, "~> 0.3.3"},
```

and all the config was followed, error are correctly reported through email and ErrorTracker. However, when I use `ErrorTracker.set_context(%{user_id: 123})`, there is zero error context coming through in ErrorTracker. It shows as `{}` in the ErrorTracker interface. This is when raised in a LiveView process.

When I change the config to:

```elixir
{:tower_email, "~> 0.5.2"},
{:error_tracker, "~> 0.4.0"},
```

And I remove the `TowerErrorTracker` reporter `config :tower, :reporters, [TowerEmail]`, then I get a full set of error context along with custom set_context values.

**Comment by grzuy** [comment]
Hey @brainlid,

Thanks for the report!

Indeed: https://github.com/mimiquate/tower_error_tracker/compare/process-context?expand=1.

It seems this is caused mainly because of the combined effects of ErrorTracker storing the context in the process dictionary, and in `tower` we're spawning a new process before calling the reporter.

I'll try to figure out a way it can be reported anyway...

**Comment by grzuy** [comment]
Having tower support something like `Tower.set_context` so that it can be sent later to all reporters is part of the plan FWIW.

**Comment by brainlid** [comment]
Thanks @grzuy! I suspected it might be a cross-process issue. I don't know if this helps, but I've previously copied Logger's internal metadata state (stored in the process) when crossing process boundaries so things like the a Plug assigned `request_id` could flow deeper into spawned workers. Perhaps something like that could help here?

**Comment by grzuy** [comment]
Yes, we would need some copying of process dictionary values most probably [here](https://github.com/mimiquate/tower/blob/9b74abf43eaa5f123fcac83952935a69ad714dbd/lib/tower.ex#L489-L493).

The same will be needed, as you say, for when reporting any `Logger.metadata`, which we'll probably will in the future.

**Comment by grzuy** [comment]
Hi @brainlid,

Just released `tower` `0.7.3` with a workaround (https://github.com/mimiquate/tower/pull/93) that I will fix this if you're using `bandit`.

To fix it for web apps using `plug_cowboy` will probably need a different workaround/approach.

**Comment by brainlid** [comment]
That fixed it for me! Thanks!

**Comment by grzuy** [comment]
> It seems this is caused mainly because of the combined effects of ErrorTracker storing the context in the process dictionary, and in `tower` we're spawning a new process before calling the reporter.

For the record, `tower` no longer spawns new process before calling the reporter(s) since `0.8.0`: https://github.com/mimiquate/tower/pull/120. Responsability of optional async processing now moved to reporters.
